/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChromeNudge: typeof import('./src/components/password-nudges/ChromeNudge.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
  }
}
